/* 
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AvisosCapApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AvisosCapApiTests
    {
        private AvisosCapApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AvisosCapApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvisosCapApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AvisosCapApi
            //Assert.IsInstanceOfType(typeof(AvisosCapApi), instance, "instance is a AvisosCapApi");
        }

        
        /// <summary>
        /// Test AvisosDeFenmenosMeteorolgicosAdversosArchivo
        /// </summary>
        [Test]
        public void AvisosDeFenmenosMeteorolgicosAdversosArchivoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fechaIniStr = null;
            //string fechaFinStr = null;
            //var response = instance.AvisosDeFenmenosMeteorolgicosAdversosArchivo(fechaIniStr, fechaFinStr);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test AvisosDeFenmenosMeteorolgicosAdversosLtimo_
        /// </summary>
        [Test]
        public void AvisosDeFenmenosMeteorolgicosAdversosLtimo_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string area = null;
            //var response = instance.AvisosDeFenmenosMeteorolgicosAdversosLtimo_(area);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
    }

}
