/* 
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PrediccionesEspecificasApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PrediccionesEspecificasApiTests
    {
        private PrediccionesEspecificasApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PrediccionesEspecificasApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrediccionesEspecificasApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PrediccionesEspecificasApi
            //Assert.IsInstanceOfType(typeof(PrediccionesEspecificasApi), instance, "instance is a PrediccionesEspecificasApi");
        }

        
        /// <summary>
        /// Test InformacionNivologica_
        /// </summary>
        [Test]
        public void InformacionNivologica_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string area = null;
            //var response = instance.InformacionNivologica_(area);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinDeMontaaTiempoActual_
        /// </summary>
        [Test]
        public void PrediccinDeMontaaTiempoActual_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string area = null;
            //string dia = null;
            //var response = instance.PrediccinDeMontaaTiempoActual_(area, dia);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinDeMontaaTiempoPasado_
        /// </summary>
        [Test]
        public void PrediccinDeMontaaTiempoPasado_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string area = null;
            //var response = instance.PrediccinDeMontaaTiempoPasado_(area);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinDeRadiacinUltravioletaUVI_
        /// </summary>
        [Test]
        public void PrediccinDeRadiacinUltravioletaUVI_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dia = null;
            //var response = instance.PrediccinDeRadiacinUltravioletaUVI_(dia);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinParaLasPlayasTiempoActual_
        /// </summary>
        [Test]
        public void PrediccinParaLasPlayasTiempoActual_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string playa = null;
            //var response = instance.PrediccinParaLasPlayasTiempoActual_(playa);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinPorMunicipiosDiariaTiempoActual_
        /// </summary>
        [Test]
        public void PrediccinPorMunicipiosDiariaTiempoActual_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string municipio = null;
            //var response = instance.PrediccinPorMunicipiosDiariaTiempoActual_(municipio);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test PrediccinPorMunicipiosHorariaTiempoActual_
        /// </summary>
        [Test]
        public void PrediccinPorMunicipiosHorariaTiempoActual_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string municipio = null;
            //var response = instance.PrediccinPorMunicipiosHorariaTiempoActual_(municipio);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
    }

}
