/* 
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValoresClimatologicosApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ValoresClimatologicosApiTests
    {
        private ValoresClimatologicosApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ValoresClimatologicosApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValoresClimatologicosApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ValoresClimatologicosApi
            //Assert.IsInstanceOfType(typeof(ValoresClimatologicosApi), instance, "instance is a ValoresClimatologicosApi");
        }

        
        /// <summary>
        /// Test ClimatologasDiarias1
        /// </summary>
        [Test]
        public void ClimatologasDiarias1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fechaIniStr = null;
            //string fechaFinStr = null;
            //var response = instance.ClimatologasDiarias1(fechaIniStr, fechaFinStr);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test ClimatologasDiarias_
        /// </summary>
        [Test]
        public void ClimatologasDiarias_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fechaIniStr = null;
            //string fechaFinStr = null;
            //string idema = null;
            //var response = instance.ClimatologasDiarias_(fechaIniStr, fechaFinStr, idema);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test ClimatologasMensualesAnuales_
        /// </summary>
        [Test]
        public void ClimatologasMensualesAnuales_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string anioIniStr = null;
            //string anioFinStr = null;
            //string idema = null;
            //var response = instance.ClimatologasMensualesAnuales_(anioIniStr, anioFinStr, idema);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test ClimatologasNormales19812010_
        /// </summary>
        [Test]
        public void ClimatologasNormales19812010_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idema = null;
            //var response = instance.ClimatologasNormales19812010_(idema);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test EstacionesPorIndicativo_
        /// </summary>
        [Test]
        public void EstacionesPorIndicativo_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string estaciones = null;
            //var response = instance.EstacionesPorIndicativo_(estaciones);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test InventarioDeEstacionesValoresClimatolgicos_
        /// </summary>
        [Test]
        public void InventarioDeEstacionesValoresClimatolgicos_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InventarioDeEstacionesValoresClimatolgicos_();
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
        /// <summary>
        /// Test ValoresExtremos_
        /// </summary>
        [Test]
        public void ValoresExtremos_Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parametro = null;
            //string idema = null;
            //var response = instance.ValoresExtremos_(parametro, idema);
            //Assert.IsInstanceOf<Model200> (response, "response is Model200");
        }
        
    }

}
