/* 
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Model429
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Model429Tests
    {
        // TODO uncomment below to declare an instance variable for Model429
        //private Model429 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Model429
            //instance = new Model429();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Model429
        /// </summary>
        [Test]
        public void Model429InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Model429
            //Assert.IsInstanceOfType<Model429> (instance, "variable 'instance' is a Model429");
        }


        /// <summary>
        /// Test the property 'Descripcion'
        /// </summary>
        [Test]
        public void DescripcionTest()
        {
            // TODO unit test for the property 'Descripcion'
        }
        /// <summary>
        /// Test the property 'Estado'
        /// </summary>
        [Test]
        public void EstadoTest()
        {
            // TODO unit test for the property 'Estado'
        }

    }

}
